=== juanjesus-14/daw1-lenguajes-de-marcas/t4-xml-dtd-xsd/a-4-5-xml-valido-a-partir-de-xsd/ticket.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="cartelera">
<xs:complexType>
<xs:sequence>
<xs:element name="ticket" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="pelicula" type="xs:string"/>
<xs:element name="fecha" type="xs:date"/>
<xs:element name="sala">
<xs:simpleType>
<xs:restriction base="xs:integer">
<xs:minInclusive value="1"/>
<xs:maxInclusive value="15"/>
</xs:restriction>
</xs:simpleType>
</xs:element>
</xs:sequence>
<xs:attribute name="id" type="xs:ID" use="required"/>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== juanjesus-14/daw1-lenguajes-de-marcas/t4-xml-dtd-xsd/a-4-5-xml-valido-a-partir-de-xsd/entrada_valida.xml
<?xml version="1.0" encoding="UTF-8"?>
<cartelera xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="ticket.xsd">

    <ticket id="t1">
        <pelicula>Torrente, presidente</pelicula>
        <fecha>2026-03-13</fecha>
        <sala>5</sala>
    </ticket>

    <ticket id="t2">
        <pelicula>Padre no hay más que uno 5</pelicula>
        <fecha>2025-06-26</fecha>
        <sala>10</sala>
    </ticket>

</cartelera>
