=== juanjesus-14/daw1-lenguajes-de-marcas/examenes/t5-examen-xslt/examenxslt/consulta.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="clinica">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="consulta" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="especie" type="xs:string"/>
                            <xs:element name="edad">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0"/>
                                        <xs:maxInclusive value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            
                            <xs:element name="fecha" type="xs:date"/>
                            
                            <xs:element name="procedimientos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tarea" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="descripcion" type="xs:string"/>
                                                    <xs:element name="precio" type="xs:decimal"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            
                            <xs:element name="prioridad">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="baja"/>
                                        <xs:enumeration value="media"/>
                                        <xs:enumeration value="alta"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                        <xs:attribute name="revision" type="xs:boolean" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== juanjesus-14/daw1-lenguajes-de-marcas/examenes/t5-examen-xslt/examenxslt/consulta.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="./consulta.xsl"?>
<clinica xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="consulta.xsd">
    
    <consulta id="C_502" revision="false">
        <nombre>Max</nombre>
        <especie>Perro</especie>
        <edad>5</edad>
        <fecha>2024-05-20</fecha>
        
        <procedimientos>
            <tarea>
                <descripcion>Vacuna Rabia</descripcion>
                <precio>35.50</precio>
            </tarea>
            <tarea>
                <descripcion>Desparasitación</descripcion>
                <precio>15.00</precio>
            </tarea>
        </procedimientos>
        
        <prioridad>media</prioridad>
    </consulta>
    
    <consulta id="C_503" revision="true">
        <nombre>Luna</nombre>
        <especie>Gato</especie>
        <edad>2</edad>
        <fecha>2024-05-21</fecha>
        
        <procedimientos>
            <tarea>
                <descripcion>Limpieza de oídos</descripcion>
                <precio>20.00</precio>
            </tarea>
        </procedimientos>
        
        <prioridad>baja</prioridad>
    </consulta>
    
</clinica>
